### ISSUE TITLE
tx "not found in RPC"

### ISSUE THREAD

**Issue by verycrypto** [bitpay/insight#395]
I'm trying to lookup an address (any address) and the interface hangs with a green "Loading Transactions" bar. If I try via the API and I check the nodejs log I see:

```
GET /api/txs/?address=1SnaVqJDQcMnANFbT2GP9cXkbAsZFdnir 200 2896ms
[transactions.js.48]:: TXid 03f839d12f236773ea974749d6a46898f12af07c6fb923288a3f63d95ab3beed not found in RPC. CHECK THIS.
```

Looking at the other calls that the interface makes... /api/addr does seem to return some info via JSON.

any ideas? thanks!

**Comment by GreydonIselmoe** [comment]
So uh, I set my txindex=1 and I still have this issue. Help?

Also, When I check addresses it has "0" for all values, and for transactions just shows the green "Loading Transactions" status.
