### ISSUE TITLE
npm start error after reinstall. 

### ISSUE THREAD

**Issue by user12312** [bitpay/insight#426]
after reinstall get error on npm start:

insight-bitcore@0.1.3 start /xxx/xxx/insight
 INSIGHT_PUBLIC_PATH=public node node_modules/insight-bitcore-api/insight.js

/xxx/xxx/insight/node_modules/insight-bitcore-api/lib/Rpc.js:7
  var RpcClient       = require('bitcore/RpcClient').class(),
                                                                                   ^
TypeError: Object function RpcClient(opts) {
  opts = opts || {};
  this.host = opts.host || '127.0.0.1';
  this.port = opts.port || 8332;
  this.user = opts.user || 'user';
  this.pass = opts.pass || 'pass';
  this.protocol = (opts.protocol == 'http') ? http : https;
  this.batchedCalls = null;
  this.disableAgent  = opts.disableAgent || false;
} has no method 'class'
    at spec

npm ERR! insight-bitcore@0.1.3 start: `INSIGHT_PUBLIC_PATH=public node node_modules/insight-bitcore-api/insight.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the insight-bitcore@0.1.3 start script.
npm ERR! This is most likely a problem with the insight-bitcore package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     INSIGHT_PUBLIC_PATH=public node node_modules/insight-bitcore-api/insight.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls insight-bitcore
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.2.0-56-generic-pae
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /mnt/drive2/insight
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! code ELIFECYCLE
npm ERR!

**Comment by AnanthKongu** [comment]
Hi,
I'm new to this, now i'm trying to setup litecoin full node with insight api, I finished litecoin node setup, but no luck with insight api, please some one help me on this, Thanks in advance.
