### ISSUE TITLE
SPV Engine for Insight

### ISSUE THREAD

**Issue by jcrubino** [bitpay/insight#455]
Anyone interested on working on a pluggable SPV network engine for insight?

Would facilitate watch only addresses and transactions not necessarily complete blockchain info; for lack of a better term.

I see a node spv wallet was started by @jgarzik & @kdrake but has not seen any development since the initial commits.

**Comment by eragmus** [comment]
@matiu Any progress on converting to Copay to SPV?

**Comment by matiu** [comment]
There is no plan to convert Copay to SPV, at least for the moment.
