### ISSUE TITLE
retrieve transaction history "since" transaction id

### ISSUE THREAD

**Issue by gordonwritescode** [bitpay/insight#513]
i would like to be able to fetch transactions that have occurred between "now" and the time of `txid`. 

this would be immensely helpful for transaction monitor applications that may go down and need to see what they missed.

**Comment by braydonf** [comment]
The `start` and `end` block height options in `node.services.address.getAddressHistory` of bitcore-node should make this possible transaction history for a group of addresses. For example, you would need to know the block height of the txid and the current height.

**Comment by braydonf** [comment]
We should add the ability to query by block height instead of only by page.

**Comment by braydonf** [comment]
We can track with: https://github.com/bitpay/insight-api/issues/428
