### ISSUE TITLE
Genesis block does not list transactions or mining subsidy

### ISSUE THREAD

**Issue by BTCTaras** [bitpay/insight#516]
Instead of listing transactions, the transaction list for block 0 will stall at a 'Loading Transactions...' progress bar. The block reward is also missing.
http://live.insight.is/block/000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f

**Comment by braydonf** [comment]
Moved to: https://github.com/bitpay/insight-api/issues/429
