### ISSUE TITLE
Informative: Running insight as a service with forever

### ISSUE THREAD

**Issue by MarkPfennig** [bitpay/insight#530]
A requirement of running a block explorer such insight, is to have it running permanently.

A clean solution to doing this, is to use `forever` an npm module. First, install forever.

    npm install -g forever

Now you can launch insight forever by using the following command

    cd insight
    BITCOIND_USER="bitcoinrpc" BITCOIND_PASS="pass" INSIGHT_NETWORK='livenet' INSIGHT_PUBLIC_PATH="public" forever start node_modules/insight-bitcore-api/insight.js

This will also restart insight if it crashes.

A full list of running forever processes can be found by calling

    forever list

To stop a process

    forever stop 0

To restart

    forever restart 0

Check the forever github for [a full list of commands and options](https://github.com/nodejitsu/forever#using-forever-from-the-command-line)

**Comment by braydonf** [comment]
There is now also this guide available: https://bitcore.io/guides/upstart-daemon
