### ISSUE TITLE
Download block data via P2P protocol

### ISSUE THREAD

**Issue by jgarzik** [bitpay/insight#531]
P2P protocol is a binary protocol, that serves blocks and TXs in network wire format.  It is preferred to download blocks via P2P.

Downloading blocks via RPC is much, much slower, and involves much internal data copying, encoding, and decoding of binary data.

Directly accessing bitcoind's blocks/blk*.dat files is problematic because this is a low level on-disk format that _just happens to be network format right now_.  Notably, these files are already not quite network format (zeros appended).  Upstream, a different on-disk format for blocks is being discussed, which would break insight sync.

**Comment by braydonf** [comment]
This has been address with bitcore-node, which queries the blocks 20x faster than RPC.
