### ISSUE TITLE
scan link on desktop crashes

### ISSUE THREAD

**Issue by bitcoinsSG** [bitpay/insight#542]
If you try clicking on the "scan" button on the top right corner on a desktop(checked on ubuntu 14) computer browser(chrome, firefox, opera), a hover window opens but disappears immediately after.

**Comment by braydonf** [comment]
QR Code scanner link is working here.

**Comment by bitcoinsSG** [comment]
yes, it's been a year since this post, and i believe it's been addressed/resolved.
