### ISSUE TITLE
Interface not updating with only RPC connection

### ISSUE THREAD

**Issue by phutchins** [bitpay/insight#554]
During setting up Insight, I noticed that you could launch the server where it connects to the RPC port only, not p2p port. The server comes up, loads the blockchain, but then does not update the front page after that. You are still able to see new blocks etc... but nothing is updated until a restart.

I'm unsure if it is intentional to allow the app to come up only connecting to the RPC port but it might should display a notification of some sort either in the console or on the front page that the connection to the P2P port is unavailable and content will not update until the connection is restored.

I'd be glad to share more info if it would be helpful.

**Comment by chrisfranko** [comment]
any fix for this yet?

**Comment by ChristianGrieger** [comment]
I also need a fix for this asap :( sitting here with a half finished explorer. Anyone here who can fix that ?
For me it tells it can't connect to socket.io data on debug window, is it that or another probmen?

**Comment by doged** [comment]
lol at best i connect to the p2p for a day or two.. at worst it takes restarting over and over every 30 seconds, and sometiems takes 20-50 tries to get it to connect and stay (for a few hours/days)

i see this issue all over github..

**Comment by braydonf** [comment]
Syncing is no longer using RPC.
