### ISSUE TITLE
Minerals (X11 POW/POS) crashing Insight at synchronization

### ISSUE THREAD

**Issue by AkiraTakizawa** [bitpay/insight#555]
Hello

I've been trying in vain to get a insight up & running for an altcoin called Minerals. It's a regular X11 POW/POS crypto. Using your original release at first, I noticed that it does not support POS transactions. SDCDev made the required modifications for that, saving a lot of work. I forked his release and started modifying things here & there to make it suitable for Minerals (no commits yet).

Unfortunately for me, it's not working as expected. The settings in the API's networks.js are correct and reflect the settings for Minerals.

When firing up insight the first time with `INSIGHT_NETWORK=livenet npm start`, it reads the genesisblock from blk0001.dat, but halts on a transaction that doesn't exist, right away:

`info: starting...`
`insight server listening on port 3000 in development mode`
`info: Seeking file to:00000c639b0fbf250ba63c6ef2952dbb44bb1051324a27383b8a56fb833d8137`
`        FOUND Starting Block!`
`info: Got 0 blocks in current DB, out of 458999 block at bitcoind`
`info: bitcoind dataDir configured...importing blocks from .dat files`
`info: First file index: 0`
`info: Starting from:  00000c639b0fbf250ba63c6ef2952dbb44bb1051324a27383b8a56fb833d8137`
`info: status: [0%]`
`Reading Blockfile /home/akira/.Minerals/blk0001.dat [236 MB]`
`{ '0': '0 of 1 peers connected' }`
`{ '0': 'connecting to 127.0.0.1:33442' }`
`{ '0': '[127.0.0.1:33442] Sending message version (99 bytes)' }`
`error: NEED_SYNC Ignoring block with non existing` `prev:25e695d4b9ecfbbdde3320bafdf5cb9eb24cb232527bbabd8642a1d1a783d91d`
`[historic_sync] ABORTED with error: NEED_SYNC Ignoring block with non existing` `prev:25e695d4b9ecfbbdde3320bafdf5cb9eb24cb232527bbabd8642a1d1a783d91d`
`{ '0': '[127.0.0.1:33442] Recieved 148 bytes of data:' }`
`{ '0': '... a1a0a2a376657273696f6e0000000000640000007bf2b1d66dea000001000000000000...' }`
`{ '0': '[127.0.0.1:33442] Received message version (100 bytes)' }`
`{ '0': '[127.0.0.1:33442] Sending message verack (0 bytes)' }`
`{ '0': '[127.0.0.1:33442] Received message verack (0 bytes)' }`
`{ '0': 'connected to 127.0.0.1:33442' }`
`[p2p_sync] Connected to 1 peer`
`{ '0': '1 of 1 peers connected' }`
`{ '0': '1 of 1 peers connected' }`

When I go to /api/sync in confirms the error: `{"status":"error","blockChainHeight":458999,"syncPercentage":"0.000","height":0,"error":"NEED_SYNC Ignoring block with non existing prev:25e695d4b9ecfbbdde3320bafdf5cb9eb24cb232527bbabd8642a1d1a783d91d","type":"from .dat Files","startTs":1411718866793,"endTs":null}`

I do not know where this 25e695d4b9ecfbbdde3320bafdf5cb9eb24cb232527bbabd8642a1d1a783d91d comes from, but it definitely does not exist. I also think it's highly unlikely that it even comes from the blockchain, or that this is some kind of obscure hidden transaction.

Thus, there is nothing left for me to do but kill the process.
When restarting it, with a fictive location for the blk0001.dat to avoid loading from file, it crashes as well:

`info: starting...`
`insight server listening on port 3000 in development mode`
`info: Previous TIP is now orphan. Back to:undefined`

`/home/akira/insight/node_modules/insight-bitcore-api/lib/BlockDb.js:119`
`      throw new Error('unable to get info for block:'+ hash);`
`            ^`
`Error: unable to get info for`
` block:29e63cc1679a47f2623404b2be13e8302f3e301ae51166d56bae186e2d325c42`
`    at /home/akira/insight/node_modules/insight-bitcore-api/lib/BlockDb.js:119:13`
`    at /home/akira/insight/node_modules/insight-bitcore-api/lib/BlockDb.js:280:30`
`    at /home/akira/insight/node_modules/insight-bitcore-api/lib/Rpc.js:98:40`
`    at IncomingMessage.<anonymous> (/home/akira/insight/node_modules/insight-bitcore-api/node_modules/bitcore/lib/RpcClient.js:203:7)`
`    at IncomingMessage.EventEmitter.emit (events.js:117:20)`
`    at _stream_readable.js:920:16`
`    at process._tickCallback (node.js:415:13)`
`npm ERR! weird error 8`
`npm WARN This failure might be due to the use of legacy binary "node"`
`npm WARN For further explanations, please read`
`/usr/share/doc/nodejs/README.Debian`
` `
`npm ERR! not ok code 0`

Block 29e63cc1679a47f2623404b2be13e8302f3e301ae51166d56bae186e2d325c42 doesn't exist either.

On the other hand, when I disable its means to read the blockfile, forcing it to use RPC to sync, everything goes fine on the initial synchronization of what Mineralsd already downloaded:

`info: status: [100%]`
`Done Syncing { status: 'finished',`
`  blockChainHeight: 10241,`
`  syncPercentage: '100.000',`
`  height: 10241,`
`  syncTipHash: undefined,`
`  error: null,`
`  type: 'from RPC calls',`
`  startTs: 1411754805592,`
`  endTs: 1411755139384 }`
`info: status: [100%]`

For testing, I tried the following situations:
* ^C to kill the npm while having loaded a few blocks: Insight resumes as if nothing happened when started
* Disconnected the internet `sudo ifdown eth1` to stop the Minerals daemon from getting new blocks after I had 100% synchronized (of ~400k blocks):  you can kill and restart Insight at will: it keeps running as expected.
* Reconnect the internet, so that it can continue loading, it crashes:

`## Retrying storeTipBlock with: 23398e684f0b1df2d1021b7b32c215f9445bdd23b623638d15f0981fa1f457f5`
`## Storing a block already. Delaying storeTipBlock with:23398e684f0b1df2d1021b7b32c215f9445bdd23b623638d15f0981fa1f457f5`
`## Retrying storeTipBlock with: 14e129f15c49bb6c206b0d8057c82d63696bdeb1a9ddb758b73209d83a0b3862`
`## Storing a block already. Delaying storeTipBlock with:14e129f15c49bb6c206b0d8057c82d63696bdeb1a9ddb758b73209d83a0b3862`
`## Retrying storeTipBlock with: 5cd02652427e7274755c6ebb36a9e0d4072cb35af99405456c011a24b934dd84`
`GET /status 200 169ms`
`[p2p_sync] Orphan block received. Triggering sync`
`GET /css/main.min.css 304 57ms`
`GET /js/vendors.min.js 304 35ms`
`GET /js/angularjs-all.min.js 304 39ms`
`GET /js/main.min.js 304 40ms`
`## Retrying storeTipBlock with: 6f03e555dee08f7c31e5bceda6aa7202a428c62858591588cd3a3cc26d77ec0a`
`[p2p_sync] Orphan block received. Triggering sync`
`error: ## Wont start to sync while status is starting`
`[p2p_sync] Done resync.`
`info: Previous TIP is now orphan. Back to:undefined`
`## Retrying storeTipBlock with: 5da9af2126d7c0ebcdb1c8d8b1739513b54d6c3d89e527e0580b55bdc02f6a53`
` `
`/home/akira/insight/node_modules/insight-bitcore-api/lib/BlockDb.js:119`
`      throw new Error('unable to get info for block:'+ hash);`
`            ^`
`Error: unable to get info for block:beeafac7a8b9697246665251215fda6c22d2410dc2cd82004e6ef2c462f3f431`
`    at /home/akira/insight/node_modules/insight-bitcore-api/lib/BlockDb.js:119:13`
`    at /home/akira/insight/node_modules/insight-bitcore-api/lib/BlockDb.js:280:30`
`    at /home/akira/insight/node_modules/insight-bitcore-api/lib/Rpc.js:98:40`
`    at IncomingMessage.<anonymous> (/home/akira/insight/node_modules/insight-bitcore-api/node_modules/bitcore/lib/RpcClient.js:203:7)`
`    at IncomingMessage.EventEmitter.emit (events.js:117:20)`
`    at _stream_readable.js:920:16`
`    at process._tickCallback (node.js:415:13)`
`npm ERR! weird error 8`
`npm WARN This failure might be due to the use of legacy binary "node"`
`npm WARN For further explanations, please read`
`/usr/share/doc/nodejs/README.Debian`
` `
`npm ERR! not ok code 0`

* ^C to kill npm and restart it to sync, like in the first situation above: crash on a transaction/block:

I tried with different blk0001.dat snapshots I made over time, they all result in the same.
A copy of the latest copy of block chain file is available here should you need it: https://dl.dropboxusercontent.com/u/2780744/blk0001.tar.xz (141 MB) It's from a few hours ago.

As far as I can see, Darkcoin's fork doesn't work either. Is there something specific I didn't pay attention to? SDCDev's fork is for a Scrypt POW/POS coin. Is there a difference in the way a blockchain is stored, depending on the currencies algorithm? bitcoin-abe seems to accept anything, but python is so resource hungry I can't host it myself on a modest server.

Does this require a (sub-)component to be thoroughly rewritten/redesigned to support X11?

Thank you in advance for your time reading this.

**Comment by genecyber** [comment]
So the problem here is simple, insight was made for Bitcoin and is a sha256 coin. The error described amongst a few threads all with differing coin hashing algo's likely all suffer the same problem. 
This line here in "insight-bitcore-api/lib/peer sync.js".

var blockHash = bitcoreUtil.formatHashFull(block.calcHash())

Looking deeper we find a hard coded reference to sha256 hashing. Which of course won't return a valid block hash on say a sCrypt block.

My quick fix to remedy this temporarily is to look for malformed hashed (no leading zeros) and fall back to RPC which naturally works because the altcoin daemons are using the correct algo to parse and store blocks.

See the patch here https://gist.github.com/genecyber/46a835038221d8e30cfb

Note: the block reader that's reads from disk also has a similar issue but hey... Teach a man to fish and all...

**Comment by luxurycoin-project** [comment]
Sorry how do you apply this patch paste that code in place of  

var blockHash = bitcoreUtil.formatHashFull(block.calcHash()) line?

**Comment by chrisfranko** [comment]
@luxurycoin-project yes

**Comment by josecelano** [comment]
Block parser does not work with the latest bitcoin core release. It works with version bitcoin-0.9.3

https://github.com/bitpay/insight/issues/585#issuecomment-74942944

**Comment by AkiraTakizawa** [comment]
@genecyber Thank you very much for your time and efforts to figure this out. I'll give this a try as soon as I find some time 🚀

**Comment by AkiraTakizawa** [comment]
Hello :smile: 

It's been a while, but I can finally take the time to apply @genecyber 's suggestion. Needless to say that it worked like a charm and I'm very happy with it. Thank you very much for you solution :bow: 

While I'm at it, I been playing a lot with Insight today. The first thing I wanted to try, is loading the blockchain from the data files. Because the altcoin I work with has a slightly different structure in its datadir, I modified nsight/node_modules/insight-bitcore-api/lib/BlockExtractor.js of my installation to reflect this. Line 12 becomes:

```var path = dataDir + '/blk*.dat';```

This way, when launchingInsight with ```BITCOIND_DATADIR=/home/akira/.Mineralscoin/livenet NODE_ENV=test INSIGHT_NETWORK=livenet npm start```, I expected to load 21500 blocks. This represents only a fraction of the actual blockchain for my test setup.

I can see that it find the blockchain data file blk0001.dat, the hash of my genesis block and the number of blocks included in this file:

```
info: insight server listening on port 3000 in test mode
info: Seeking file to:00000c639b0fbf250ba63c6ef2952dbb44bb1051324a27383b8a56fb833d8137
	FOUND Starting Block!
info: Got 0 blocks in current DB, out of 21500 block at bitcoind
info: bitcoind dataDir configured...importing blocks from .dat files
info: First file index: 0
info: Starting from:  00000c639b0fbf250ba63c6ef2952dbb44bb1051324a27383b8a56fb833d8137
info: status: [0%]
Reading Blockfile /home/akira/.Mineralscoin/livenet/blk0001.dat [12 MB]
Finished all files
info: status: [0%]
{ '0': 'connecting to 127.0.0.1:33442' }
{ '0': 'connected to 127.0.0.1:33442' }
```

Unfortunately for me, it seems to completely skip the file. There is also no information about it moving on to RPC. When I move the actual complete database of 768 MB, it also immediately returns that it finished, while loading such file would probably take several hours. Are altcoins different in the way they store their blockchain data? Did I oversee something in the configuration?

In my browser, I can see it loading the blocks when I press F5 to refresh the home page and ultimately, the 21500 blocks are loaded. How the blocks got loaded is a mystery. I think it loaded them over RPC, considering the last two lines in the console output. The actual blockchain has over 1.4 million blocks and importing this via RPC will be quite slow from what I can read in other topics here.

Then I have a question about the message "Unparsed address [0]" for certain transactions:

![insight3](https://cloud.githubusercontent.com/assets/8864848/7481852/8be5189c-f373-11e4-9150-eeb91c78ed6d.png)

This transaction returns the following using the cli:

```
getrawtransaction c861d37d051b0fce77bd5a62035b34954b67fbd1f8b5b11bb74790b74d2bdbed
￼
REPLY: 0100000084b9a2530161270e0171c1930cb8967bd3f12a306dd493aaa10caece9518b80952542eab7a010000006b483045022100c8fa4e81dbe2926b86c39dcbd14c54deca323928340e4ca8085fd6dc336862e7022020425f66cd3a6d0a96c2ee4b19572755e4febce6be5acd5d233e04c3c8f8f927012102beb112dc3eccfaf27bde0131bc459211208d19cffa08adb1b724821d465b3494ffffffff03000000000000000000c0583e9900000000232102beb112dc3eccfaf27bde0131bc459211208d19cffa08adb1b724821d465b3494ac1ab5529900000000232102beb112dc3eccfaf27bde0131bc459211208d19cffa08adb1b724821d465b3494ac00000000
￼
decoderawtransaction 0100000084b9a2530161270e0171c1930cb8967bd3f12a306dd493aaa10caece9518b80952542eab7a010000006b483045022100c8fa4e81dbe2926b86c39dcbd14c54deca323928340e4ca8085fd6dc336862e7022020425f66cd3a6d0a96c2ee4b19572755e4febce6be5acd5d233e04c3c8f8f927012102beb112dc3eccfaf27bde0131bc459211208d19cffa08adb1b724821d465b3494ffffffff03000000000000000000c0583e9900000000232102beb112dc3eccfaf27bde0131bc459211208d19cffa08adb1b724821d465b3494ac1ab5529900000000232102beb112dc3eccfaf27bde0131bc459211208d19cffa08adb1b724821d465b3494ac00000000

REPLY:
￼
{
  "txid" : "c861d37d051b0fce77bd5a62035b34954b67fbd1f8b5b11bb74790b74d2bdbed",
  "version" : 1,
  "time" : 1403173252,
  "locktime" : 0,
  "vin" : [
    {
      "txid" : "7aab2e545209b81895ceae0ca1aa93d46d302af1d37b96b80c93c171010e2761",
      "vout" : 1,
      "scriptSig" : {
	"asm" : "3045022100c8fa4e81dbe2926b86c39dcbd14c54deca323928340e4ca8085fd6dc336862e7022020425f66cd3a6d0a96c2ee4b19572755e4febce6be5acd5d233e04c3c8f8f92701 02beb112dc3eccfaf27bde0131bc459211208d19cffa08adb1b724821d465b3494",
	"hex" : "483045022100c8fa4e81dbe2926b86c39dcbd14c54deca323928340e4ca8085fd6dc336862e7022020425f66cd3a6d0a96c2ee4b19572755e4febce6be5acd5d233e04c3c8f8f927012102beb112dc3eccfaf27bde0131bc459211208d19cffa08adb1b724821d465b3494"
      },
      "sequence" : 4294967295
    }
  ],
  "vout" : [
    {
      "value" : 0.00000000,
      "n" : 0,
      "scriptPubKey" : {
	"asm" : "",
	"type" : "nonstandard"
      }
    },
    {
      "value" : 25.71000000,
      "n" : 1,
      "scriptPubKey" : {
	"asm" : "02beb112dc3eccfaf27bde0131bc459211208d19cffa08adb1b724821d465b3494 OP_CHECKSIG",
	"reqSigs" : 1,
	"type" : "pubkey",
	"addresses" : [
	  "MKbFFBe3LP8KptyKVSz32f5KAHiD1uWx52"
	]
      }
    },
    {
      "value" : 25.72334362,
      "n" : 2,
      "scriptPubKey" : {
	"asm" : "02beb112dc3eccfaf27bde0131bc459211208d19cffa08adb1b724821d465b3494 OP_CHECKSIG",
	"reqSigs" : 1,
	"type" : "pubkey",
	"addresses" : [
	  "MKbFFBe3LP8KptyKVSz32f5KAHiD1uWx52"
	]
      }
    }
  ]
}
```

Some transactions give the description "Unparsed Address", sometime together with "Value Error" as the example above. From what I could see in the decoded raw output for that second transaction, "Unparsed Address [U]" there is because the transaction itself contains no value. Could this be due to the minting of a few coins as this block is part in the Proof-Of-Stake phase?

The value error however, is puzzling me. 51.43334362 coins are sent to MKbFFBe3LP8KptyKVSz32f5KAHiD1uWx52, but the "senders" address and amount are unknown, which make me also believe it's a POS transaction.

The decoded raw output how that the "input" (can you call it that way?) consists of two separate sources (redemption script addresses?) with a value of 25.71000000 and 25.72334362, corresponding to this 51.43334362 coins received by MKbFFBe3LP8KptyKVSz32f5KAHiD1uWx52.

Where should I look if I want to make it show these amounts?

And finally, I also noticed that the very first transaction of the blockchain for the altcoin I work with cannot be loaded. Nothing unexpected here, but the UI tries to load this transaction forever. In the console output it regularly returns:

```[transactions.js.48]:: TXid 18bf53ed0bbbc417c8e2d7993294dba71e1ba10697c9289c617ee02108bb197c not found in RPC. CHECK THIS.```

Would it be useful to have Insight not even try to load this at all for block 0 of any crypto?

I hope I'm not annoying you with my questions. It's all fairly new to me and not having coded since university over 10 years ago, this is getting very exciting for me :grin: 

Thank you very much for your time and I look forward to any reply, tip, push in a certain direction, suggestions,... anything at all :bulb:

**Comment by AkiraTakizawa** [comment]
Finally got it up & running.
Latest transaction still need some attention as well as coinbase & coinstake for Proof-Of-Work.

**Comment by doged** [comment]
@AkiraTakizawa did you have to add changes for PoS, and if so, what kind?

**Comment by AkiraTakizawa** [comment]
I didn't do anything special yet. I just worked on identifying the parts that need to be worked on, both in terms of additional information the daemon returns with its transactions and some cosmetic changes to reflect this information. There are other problems I cannot solve, such as the node process stalling, dropping all connections to Bitcore and clogging every single bit of RAM it can get it's hands on. For now, I unfortunately don't have much time to further look into this.

**Comment by doged** [comment]
im also using a scrypt coin, and i applied the patch, but i am still getting the 

info: Previous TIP is now orphan. Back to:undefined

/root/insight-doged/node_modules/insight-bitcore-api/lib/BlockDb.js:118
      throw new Error('unable to get info for block:'+ hash);
            ^
Error: unable to get info for block:5df85fb3527bcd4b8315c9321c8d7a8373bae2b43b74fe85de13574f9586a3b1

----------------------------------------------------------

that block hash is block #5

**Comment by neurocis** [comment]
Has there been any progress on this?

**Comment by justinvforvendetta** [comment]
@neurocis after alot of tinkering i got it working.. its live at http://darkchain.link

**Comment by neurocis** [comment]
@justinvforvendetta @AkiraTakizawa Cool, I had meant to ping-back on this ... I did get this running for PIGGY X11/POS/POW. Repo is https://github.com/TeamPiggyCoin/PiggyInsight.

Looks good, I will have to take a look at your repo to skin for PIGGY.

I can load all PoW blocks direct from blockfile, I am still failing on the first PoS block. However RPC works fine. If DOGED is strictly scrypt you could probably load from the .blk file w/an scrypt module in the API repo.
