### ISSUE TITLE
npm start fails with ELIFECYCLE 

### ISSUE THREAD

**Issue by victor1342** [bitpay/insight#559]
I get an ELIFECYCLE (details below) when running npm start from the insight directory (win7 64-bit). It's strange because insight-api part of it does seem to work well (i.e. if I go to node_modules/insight-bitcore-api and run node insight.js I have full use of the insight-api). It's probably something very minor, but after an entire day I'm unable to find it. Any suggestions would be appreciated.

Full error details are as follows:

0 info it worked if it ends with ok
1 verbose cli [ 'c:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@1.4.28
3 info using node@v0.10.32
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart insight-bitcore@0.2.5
6 info start insight-bitcore@0.2.5
7 verbose unsafe-perm in lifecycle true
8 info insight-bitcore@0.2.5 Failed to exec start script
9 error insight-bitcore@0.2.5 start: `INSIGHT_PUBLIC_PATH=public node node_modules/.bin/insight-bitcore-api`
9 error Exit status 1
10 error Failed at the insight-bitcore@0.2.5 start script.
10 error This is most likely a problem with the insight-bitcore package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     INSIGHT_PUBLIC_PATH=public node node_modules/.bin/insight-bitcore-api
10 error You can get their info via:
10 error     npm owner ls insight-bitcore
10 error There is likely additional logging output above.
11 error System Windows_NT 6.1.7601
12 error command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
13 error cwd c:\Users\z\rep\insight
14 error node -v v0.10.32
15 error npm -v 1.4.28
16 error code ELIFECYCLE
17 verbose exit [ 1, true ]

**Comment by braydonf** [comment]
This is outdated.
