### ISSUE TITLE
Can't sync: NEED_SYNC Ignoring block with non existing prev

### ISSUE THREAD

**Issue by jl2035** [bitpay/insight#585]
Was this already answered somewhere? I've been here: https://github.com/bitpay/insight-api/issues/200, and nobody seems to be able to help this guy.

Than here: https://github.com/bitpay/insight-api/issues/21
But my blk00000.dat file looks ok.

My bitcoind is also fine. All synched and txindex=1 added to the conf.

The error:
NEED_SYNC Ignoring block with non existing prev:00000000f7b6ea92bd64f943a327f6b19ed7799c42a7e284ba6ec1888289a87e

**Comment by Helios-vmg** [comment]
I'm getting this same error. My bitcoind is working fine, as well, but when insight tries to do the indexing, it only gets to 0.7% and then errors. I'm using the testnet, if it's relevant.

**Comment by jl2035** [comment]
I'm using livenet. It always stoppes at block 2643.

Damn.. it's been more than two months and i haven't got a single clue about this bug.

**Comment by srw** [comment]
Same issue here.

**Comment by brsq** [comment]
Are you using Bitcoin Core 0.10 or higher? New versions of bitcoind store blocks out of order which breaks Insight's block parser. You need to use 0.9.4, or wait for a rewrite of bitcore (not to be confused with Bitcoin Core, bitcore is JavaScript and what powers Insight).

**Comment by jl2035** [comment]
wasn't there another comment here with some solution? why in the world would poster remove it?

**Comment by josecelano** [comment]
My blk00000.dat file is also ok and I get the same error.

Sync using RPC seems to work:

````
insight/node_modules/insight-bitcore-api/util/sync.js -D -v --rpc
````

sync.js options:
````
  .option('-D --destroy', 'Remove current DB (and start from there)', 0)
  .option('-S --startfile', 'Number of file from bitcoind to start(default=0)')
  .option('-R --rpc', 'Force sync with RPC')
  .option('--start [hash]', 'StartAt block')
  .option('--stop [hash]', 'StopAt block')
  .option('-v --verbose', 'Verbose 0/1', 0)
``````

From: https://github.com/bitpay/insight-api/blob/master/util/sync.js

**Comment by jl2035** [comment]
I just found that comment! It was still in my mail inbox?
So either this guy doesn't want to help us for some reason, or he removed the comment bacause this is not really the solution.. anyway.. I'm pasing his comment.

"Are you using Bitcoin Core 0.10 or higher? New versions of bitcoind store blocks out of order which breaks Insight's block parser. You need to use 0.9.4, or wait for a rewrite of bitcore (not to be confused with Bitcoin Core, bitcore is JavaScript and what powers Insight)."

**Comment by josecelano** [comment]
Thanks @jl2035 . I have been reached the same conclusion. I will try with previous version, but It is strange becuase there are issues with the same problem since some months ago. Perhaps this error happens between Bitcoin Core update and their new release to adapt the parser (every time there is a new bitcoin core version). In that case they should ckeck the bitcoind version and throw an error when is not compatible, or at least add it to requirements section in docs.

**Comment by josecelano** [comment]
It is working with version bitcoin-0.9.3

**Comment by jl2035** [comment]
yes.. it is also working for me.. should we close this issue?

**Comment by josecelano** [comment]
:+1:

**Comment by rromanchuk** [comment]
Wait, why is this closed?

**Comment by jl2035** [comment]
Because we found a workaround - use bitcoin 0.9.3
The solution would be to rewrite bitcore, but that's another story.

**Comment by rromanchuk** [comment]
lol, so you're saying this project is essential dead?

**Comment by jl2035** [comment]
I tried using Bitcoin-abe.. but that was even worse.

You may be right. It looks like bitpay is abandoning this project and we are on our own.

**Comment by eordano** [comment]
We are working on making insight better and rebranding it `bitcore-node` (also at some point hoping to get it to be a full node using libconsensus). We already took `bitcore` and reworked it so it is easy to use and reliable, and are doing the same for this blockchain explorer. We've been working on it for some time now and will have updates in the next few weeks. Thanks!

**Comment by jl2035** [comment]
Oh.. so it's not. But in the future please.. can you guys pay more attention to the issues like this one?

For two months we were in dark until that guy posted the comment about "blocks out of order", who also then immediately erased the comment (thankfully I have email notifications enabled).

**Comment by matiu** [comment]
Please note also that insight-api should work OK using RPC sync (instead of file sync) with bitcoind 0.10

**Comment by rromanchuk** [comment]
@matiu does the daemon need to be forced into RPC too? or does it only matter for utils/sync.js. What about when it tries to catch up on reboot after being idle

**Comment by matiu** [comment]
The current logic is at:

https://github.com/bitpay/insight-api/blob/master/lib/HistoricSync.js#L263

To use RPC:
 - `forceRPC` must be issued (only possible with `util/sync`
 - or `dataDir` must be undefined (this can be done by commenting this line
https://github.com/bitpay/insight-api/blob/master/config/config.js#L77
at config.js)
 - or , it is a restart, sync percentage must be > 96%



On Mon, Mar 9, 2015 at 2:05 PM, Ryan Romanchuk <notifications@github.com>
wrote:

> @matiu <https://github.com/matiu> does the daemon need to be forced into
> RPC too? or does it only matter for utils/sync.js. What about when it tries
> to catch up on reboot after being idle
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/insight/issues/585#issuecomment-77896553>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by rromanchuk** [comment]
got it, thanks @matiu for fishing that out for me

**Comment by jl2035** [comment]
yeah.. thanks for sharing that, @maitu

**Comment by matiaspando** [comment]
There is a new way to force RPC sync, you must set the environment variable INSIGHT_FORCE_RPC_SYNC = 1

**Comment by lightlist** [comment]
The environment variable INSIGHT_FORCE_RPC_SYNC=1 didn't work for me, but using RPC by commenting the line
dataDir: dataDir,
worked, it just was https://github.com/bitpay/insight-api/blob/master/config/config.js#L78 now

Thanks for your help

**Comment by aasheikh** [comment]
@lightlist , that has worked for me too!

 Thanks,

**Comment by kundansmart501** [comment]
Hey,

I have commented the line dataDir: dataDir, as //dataDir: dataDir, .
But I am getting same error that tells to set environment variable INSIGHT_FORCE_RPC_SYNC=1.

Did , I miss any thing ?

Thanks,
