### ISSUE TITLE
Restarting insight creates a duplicate block

### ISSUE THREAD

**Issue by will123195** [bitpay/insight#589]
I'm using upstart on ubuntu. Every time I restart insight a duplicate block is created.

```
sudo restart insight
```

![image](https://cloud.githubusercontent.com/assets/242760/5407466/2e4e0fae-8195-11e4-9ba0-509b3d0c561f.png)

**Comment by braydonf** [comment]
This is outdated, as things have significantly changed with storing information about the blockchain, and should no longer be an issue.
