### ISSUE TITLE
Can't connect to bitcoind to get live updates from the p2p network

### ISSUE THREAD

**Issue by nuggetbram** [bitpay/insight#593]
The coin's p2p port is 11036, I can telnet to it etc, yet for some reason insight cannot connect. (Tried connecting to bitcoind at 127.0.0.1:11036 and failed.)

Was there a fix to this issue? Apart from this, the whole thing syncs and works perfectly!

Ubuntu 140.4 LTS

**Comment by chrisfranko** [comment]
what's the coins protocol version?

**Comment by doged** [comment]
lol at best i connect to the p2p for a day or two.. at worst it takes restarting over and over every 30 seconds, and sometiems takes 20-50 tries to get it to connect and stay (for a few hours/days)

i see this issue all over github..

**Comment by chrisfranko** [comment]
I run into the saaaaame problem.

**Comment by braydonf** [comment]
This is now outdated, bitcoind is now running in the same process.
