### ISSUE TITLE
insight connected but not via RPC Bitcoin

### ISSUE THREAD

**Issue by makabress** [bitpay/insight#596]
hi insight is connected but i can't get history of adresse or Tx , i can see newest block and Tx not the older

info: insight server listening on port 3000 in development mode
{ '0': [Error: Could not connect to bitcoin via RPC: connect ECONNREFUSED] }
error: Could not connect to bitcoin via RPC: connect ECONNREFUSED
{ '0': 'connecting to 127.0.0.1:8333' }
{ '0': 'connected to 127.0.0.1:8333' }

**Comment by makabress** [comment]
and iget this in http://127.0.0.1:3000/api/sync {"status":"error","syncPercentage":"NaN","height":0,"error":"Could not connect to bitcoin via RPC: connect ECONNREFUSED"}

http://127.0.0.1:3000/api/peer
{"connected":true,"host":"127.0.0.1","port":"8333"}

**Comment by maraoz** [comment]
Do you have a bitcoind instance running and configured? See https://github.com/bitpay/insight-api/blob/master/README.md#prerequisites

**Comment by makabress** [comment]
yes installed two time and downloaded Bitcoin blockcain and sync two time but i have the same problem can not see the old TX

**Comment by makabress** [comment]
now im geting this error

npm ERR! Linux 3.16.0-23-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.11.15
npm ERR! npm  v2.1.6
npm ERR! code ELIFECYCLE

npm ERR! base58-native@0.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the base58-native@0.1.2 install script.
npm ERR! This is most likely a problem with the base58-native package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls base58-native
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/insight/npm-debug.log

**Comment by maraoz** [comment]
do: 
```
rm -rf node_modules/
npm install
```

**Comment by makabress** [comment]
same problem 

info: insight server listening on port 3000 in development mode
{ '0': [Error: Could not connect to bitcoin via RPC: connect ECONNREFUSED] }
error: Could not connect to bitcoin via RPC: connect ECONNREFUSED
{ '0': 'connecting to 127.0.0.1:8333' }
{ '0': 'connected to 127.0.0.1:8333' }

**Comment by maraoz** [comment]
are you running on the correct port?
are you running insight with the correct environment variables? https://github.com/bitpay/insight-api/blob/master/README.md#configuration
did you configure the user and password correctly?

**Comment by makabress** [comment]
yes , yes and yes using rpcuser=user
rpcpassword=pass nothing special

so im installing a new clean ubuntu 14.10 in a vm session and will retry all the install to see if the problem persist

**Comment by makabress** [comment]
and now it's this

info: insight server listening on port 3000 in development mode
info: Previous TIP is now orphan. Back to:undefined

/home/me/insight/node_modules/insight-bitcore-api/lib/BlockDb.js:118
      throw new Error('unable to get info for block:'+ hash);
            ^
Error: unable to get info for block:000000001f60af4c8f53aa7d69174c8cfdab92d9827bed02172cf0d23c15301a
    at /home/me/insight/node_modules/insight-bitcore-api/lib/BlockDb.js:118:13
    at /home/me/insight/node_modules/insight-bitcore-api/lib/BlockDb.js:279:30
    at /home/me/insight/node_modules/insight-bitcore-api/lib/Rpc.js:88:40
    at IncomingMessage.<anonymous> (/home/siclop/insight/node_modules/insight-bitcore-api/node_modules/bitcore/lib/RpcClient.js:203:7)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

**Comment by makabress** [comment]
resolved by removing all file in .insight , for the first time it's syncing

**Comment by makabress** [comment]
any way to speed up insight syncing ? after 15 hour im only synced at 55%
thank you

**Comment by makabress** [comment]
the only way to speed up this sync , is some one with synced insight have to compress and upload Blocks and Txs folder from .insight 
after 24 Hour im at 60% that will take days

**Comment by makabress** [comment]
lol after 90 % i have this errror info: insight server listening on port 3000 in development mode
error: Previous Tip block tip height differs by 341846. Please delete and resync (-D)

**Comment by ladhitya** [comment]
Have you resolved this yet ? because I have similar problem. I can even do /api/sync nor /api/status?q=getinfo

**Comment by chrisfranko** [comment]
From the error above "block tip differs by x, please resync" try this

![image](https://cloud.githubusercontent.com/assets/3543217/6637714/3e8906f6-c954-11e4-90b2-805b081bd001.png)

**Comment by GreydonIselmoe** [comment]
For me, I had to use the patch listed here: https://gist.github.com/genecyber/46a835038221d8e30cfb

To force an RPC sync when a new block is found

**Comment by braydonf** [comment]
Outdated as bitcoind is now running in the same process.
