### ISSUE TITLE
SocketIO tx does not include tx outputs - vastly reducing usefulness

### ISSUE THREAD

**Issue by tkhaew** [bitpay/insight#601]
I guess this is by design but I'd argue this makes the insight socketio much less useful.

If someone wants to make an app to monitor trxs then using this socketio they have to make massive amounts of web calls to get the useful info because the tx hash on it's own is useless. Blockchain.info really has the right idea here by including tx.out they enable people to build apps that can do useful things without hitting a webserver for every single unconfirmed trx.

Just a suggestion. If you want devs to build on insight it would be more useful to have tx info here, or maybe I'm really missing something about the intent of using Insight.

**Comment by maraoz** [comment]
Agreed. Thanks for the feedback. We're currently designing a new API and it's useful to know this.

**Comment by tkhaew** [comment]
Thanks for your reply. I always wonder if it's worth saying anything. 

Another thing is that for a long time I could not use the socketIO at all from Python, my preferred language. Just a couple days ago the available socketIO-client module was fixed and now (0.6.1) works with socketIO version 1.0+. I can report that it works accessing insight and if there is interest in sample code for using that I'd be happy to post as a gist or something. 

I've been using websocket with blockchain.info for a while, in combination with sqlite to get and store data. I was intending to modularize my program so it could failover to insight or even bitcoind rpc.

**Comment by maraoz** [comment]
Yes, please share your python code :)
Thanks again

**Comment by tkhaew** [comment]
It's very simple. Just my barely got started and then I noticed the "block" message doesn't work. If run at cmd line it does dump what it gets.

https://gist.github.com/tkhaew/3f83c5bddecdf00d1a6a
