### ISSUE TITLE
Yet another cant connect to P2P network + How to change protocol version?

### ISSUE THREAD

**Issue by roam93** [bitpay/insight#603]
Im attempting to run bitpay-insight against an altcoin base. It happily initially syncs using rpc calls, but it fails to connect to the p2p network and never updates any blocks until it restarts again.

I suspect i need to change the protocol version (its 7003 on this altcoin), but im not sure how. I did try export bitcoind_proto= 7003 but it doesnt seem to work.

Secondly, does anyone have any up to date instructions on installing? Do i need both insight and insight api? My understanding was insight would automatically pull insight-api.

Thanks in advance.

**Comment by doged** [comment]
lol at best i connect to the p2p for a day or two.. at worst it takes restarting over and over every 30 seconds, and sometiems takes 20-50 tries to get it to connect and stay (for a few hours/days)

i see this issue all over github..

**Comment by braydonf** [comment]
bitcoind is now running in the same process.
