### ISSUE TITLE
Issue starting insight

### ISSUE THREAD

**Issue by vdidonato** [bitpay/insight#609]
Hello I have a bitcoin daemon running with this conf

rpcuser=user
rpcpassword=pass
txindex=1
rpcallowip=127.0.0.1

and I'm following this guide: https://github.com/bitpay/insight-api to install the insight-api.
When I run node insight.js I get this error message and I do not understand how to fix it:

info: insight server listening on port 3001 in development mode
{ '0': [Error: Could not connect to bitcoin via RPC: connect ECONNREFUSED] }
error: ERROR  Error: Could not connect to bitcoin via RPC: connect ECONNREFUSED
    at ClientRequest.<anonymous> (/home/bitcoin/Desktop/insight-api/node_modules/bitcore/lib/RpcClient.js:207:15)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1547:9)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)

could anybody help? Thanks!

**Comment by GreydonIselmoe** [comment]
You'll need server=1 and listen=1 in that conf, as well.
I'd also start it with livenet enabled, that way you're pointing towards the proper ports. Do that with:
INSIGHT_NETWORK=livenet npm start
Is this for bitcoin or an altcoin?

**Comment by braydonf** [comment]
Outdated as bitcoind now runs in the same process.
