### ISSUE TITLE
Loading transactions takes forever for specific addresses

### ISSUE THREAD

**Issue by dskloet** [bitpay/insight#610]
On testnet, I just tried to make a transaction from 2N2x61AwYDS6wMiY7PeMEhuDaLzfa119vFL to mq48weNketL7CaQTXDZmZ1d6B1pAno4zu6. I wasn't sure if it worked so I wanted to check on insight but insight doesn't show any transactions (just loading forever) for either address even though it doesn't seem to have problems with other addresses.

https://test-insight.bitpay.com/address/2N2x61AwYDS6wMiY7PeMEhuDaLzfa119vFL
https://test-insight.bitpay.com/address/mq48weNketL7CaQTXDZmZ1d6B1pAno4zu6

**Comment by braydonf** [comment]
These are loading fine here, this issue was likely fixed with several of the performance improvements.
