### ISSUE TITLE
Block list not updating when syncing from RPC

### ISSUE THREAD

**Issue by GreydonIselmoe** [bitpay/insight#612]
I've used this "patch" https://gist.github.com/genecyber/46a835038221d8e30cfb since I was getting an error each time a new block was found, but now block list isn't updating when a new block is found.

Also, the block was found x minutes ago feature is stuck, with time since block find isn't updating until you refresh the page.

I tried adding a window.location.reload(true); 
line, yet that just seems to break the server. Any thoughts?

**Comment by braydonf** [comment]
Outdated as syncing is no longer using RPC.
