### ISSUE TITLE
Bug: viewing these addresses get stuck at "Loading Transactions..."

### ISSUE THREAD

**Issue by chickenlittle** [bitpay/insight#615]
See. https://insight.bitpay.com/address/1BhhX77zfV3KA5PTNTLuUHjFqfHCSoG9uE and 
 https://insight.bitpay.com/address/1MSC85oiuviKhVGrsgHQbagHaREMvDsCc5
https://insight.bitpay.com/address/1A2FJLox8Xb8uf2yh1C8CQLkGQ27kCSbdH

Also getting nulls when fetching tx for these addresses with the api, which is probably related to what's going on above. Ex:
https://insight.bitpay.com/api/addrs/1MycQBsByXU1vUzcS3Q4Kfuny5Aim6hpW4,1DYD58EaEZkmvnLQVLqiYkxh7vWEnXP5bD,1JknKViKXwee9sSKdkRAmt7c691n1UWs5,1xMKvanXBntFM3mbtDiJVibVkzSyS4EQD,1Na1CDz7xWihyX6sj5TEaCyP9kAsBS6A63,1MSC85oiuviKhVGrsgHQbagHaREMvDsCc5,1N5MUfRS9P5N52XQmXansTCQwf3P979bS3,1BhhX77zfV3KA5PTNTLuUHjFqfHCSoG9uE/txs

**Comment by braydonf** [comment]
These are all loading fine here.
