### ISSUE TITLE
Bitcoin Core version >0.10 only works with RPC sync 

### ISSUE THREAD

**Issue by prabjot678** [bitpay/insight#616]
I am just getting this error Bitcoin Core version >0.10 only works with RPC sync  when i starting insight. it just telling me to add env varibale like "Set the env variable INSIGHT_FORCE_RPC_SYNC = 1",but i am stuck here, i  just add it to bashrc,but didn't resolve problem,guys help how to and where to add it

Thanks in advance

**Comment by thesoftwarejedi** [comment]
INSIGHT_FORCE_RPC_SYNC = 1 will only work with the latest insight-api version, which the insight package does not install.  I do not think the insight-api team released a new version to npm after patching the insight-api code to support that parameter.
There are 2 options:
- pull the latest insight-api to use with insight (see the readme for directions on developing for both(?)).  This may work, or perhaps you're knowledgable about updating the code_package folder to the latest using npm or git or such.  I'd love someone knowledgable about how to release insight-api to a new version via npm to comment here.  That's all that needs to happen.
- modify the node_packages/insight-api folder as per this suggestion in the insight-api issue tracker: https://github.com/bitpay/insight/issues/585#issuecomment-77900341

**Comment by prabjot678** [comment]
@thesoftwarejedi  thanks for the nice explanation,my insight version was ok,i have to add env varaible in config.js file,now it is working fine

**Comment by thesoftwarejedi** [comment]
This issue can be closed.
