### ISSUE TITLE
Call API with bloom filters.

### ISSUE THREAD

**Issue by ianpurton** [bitpay/insight#618]
Currently if I want a balance for an address then I give away some privacy as the API knows the address I'm interested in.

i.e. https://test-insight.bitpay.com/api/addr/mqdfWTbyZGHANkidLijPjR4La63X49DJxT

However, with bloom filters. https://github.com/bitcoin/bips/blob/master/bip-0037.mediawiki I could call the API and only leak a small amount of information. Although I would get back more data than I need.

Nice explanation of bloom filters here http://billmill.org/bloomfilter-tutorial/

So instead I pass a hash of the key I'm interested in, and you pass me balances for all addresses that match that hash i.e.
https://test-insight.bitpay.com/api/addr/jxdT,Hf4r/bloom

**Comment by braydonf** [comment]
Very similar to: https://github.com/bitpay/insight/issues/476
