### ISSUE TITLE
"npm install" fails with current npm/nodejs from latest ubuntu LTS (14.04 trusty)

### ISSUE THREAD

**Issue by sneak** [bitpay/insight#622]
distro nodejs version 0.10.25~dfsg2-2ubuntu1

distro npm version 1.3.10~dfsg-1

insight current as of rn (79341717ec5)

npm-debug.log is at https://gist.githubusercontent.com/anonymous/cff1f3b8eaa75cdf24ec/raw/npm-debug.log

**Comment by gregtampa** [comment]
think i have same error

**Comment by braydonf** [comment]
Installation should be improved, please see: https://bitcore.io/guides/full-node
