### ISSUE TITLE
what is the problem

### ISSUE THREAD

**Issue by coingeek** [bitpay/insight#627]
what is the problem how i can solve it.

{ '0': 'connecting to 127.0.0.1:35373' }

info: Previous TIP is now orphan. Back to:undefined

/rblockex/insight/node_modules/insight-bitcore-api/lib/BlockDb.js:118
      throw new Error('unable to get info for block:'+ hash);
            ^
Error: unable to get info for block:fbb67095000e45943345194b4e3e22158396449b184d3cdb598b3c39a6abefae
    at /rblockex/insight/node_modules/insight-bitcore-api/lib/BlockDb.js:118:13
    at /rblockex/insight/node_modules/insight-bitcore-api/lib/BlockDb.js:279:30
    at /rblockex/insight/node_modules/insight-bitcore-api/lib/Rpc.js:88:40
    at IncomingMessage.<anonymous> (/rblockex/insight/node_modules/insight-bitcore-api/node_modules/bitcore/lib/RpcClient.js:203:7)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0

**Comment by braydonf** [comment]
This is outdated.
