### ISSUE TITLE
Insight Explorer: Memory Issues

### ISSUE THREAD

**Issue by dan4funnyc** [bitpay/insight#628]
I recently spun up a full node on a VPS with a 90 GB hard disk. The full node has been functioning so nicely that I opted to install Insight explorer to access and visualize the node's data.

Ever since installing it and first running, the Insight database has taken up a massive amount of hard disk space and isn't done configuring yet! As I stand, when I connect to my webserver to check Insight's status, it says that syncing only at 73% (after 2 days!). I've noticed that over the past two days, the insight webserver has gotten much slower also.

Overall, in terms of hard disk space, I've used up 73 GB of space. Considering that the blockchain size is ~30GB, his would imply that Insight has filled up at least an extra 30GB. 

Is this normal? Can it be reigned in? Has anyone here had any experience with setting up the Insight explorer?

Any help would be immensely appreciated.
Thanks in advance!

**Comment by carnesen** [comment]
Insight syncs the whole block chain to its own embedded database. So in
that sense the disk usage is normal. Its possible to reign that in in the
sense that I can't see any good technical reason why it needs to sync data
that's already readily available through the peer-to-peer and remote
procedure call interfaces of Bitcoin Core. But that's currently what
Insight is set up to do. The plan for bitcore-node, the successor to
Insight, is to have bitcoind running as a linked library within a Node.js
application. Then it will no longer have to sync the data. Unfortunately
development on Insight and bitcore-node has slowed to a crawl and both
currently sync all the data.

I'm working on an alternative Insight-like project, [Satoshi TV](
https://github.com/carnesen/satoshi-tv) but like bitcore-node, it's still
under development. Also like bitcore-node, it doesn't require a full sync
of the database; it runs on top of Bitcoin Core as a light-weight web
service. Contributions welcome!!!

**Comment by matiu** [comment]
@dan4funnyc Yes,  that HD usage is normal, insight use many indexes not present at bitcoind,that that is why it uses more space (and actually that is the hole point of insight: be able to query address balances).

You can get much high sync speed by using 'file sync'. See the Readme. You need to use bitcoind 0.9.5 for that.

@carnesen Insight builds new indices to be able to query the blockchain using addresses (ie: what is the balance of certain address). That information is not available for all addresses in bitcoind. You are wrong that bitcore-node does not need that: It does need to fully sync before having meaningful data. There is no way to obtain that information only with bitcoind.

**Comment by carnesen** [comment]
True, bitcoind doesn't maintain an address index. So any insight-api-like project either needs to build that index itself or use the patched version of Bitcoin Core that maintains an address index. In either case, the address index should only occupy a fraction of the space needed for the entire block chain. Transactions and blocks are both stored and indexed by bitcoind, so in theory insight-api need not do so itself separately. In my experience both as someone who has tried and failed to deploy insight-api and who watches these repos on GitHub, the sync is the #1 usability issue and it could and should be "reigned in". 

I've been assuming that once bitcore-node completed the transition to using bitcoind.js, it would no longer sync the block chain data, only build the address index. I may be mistaken about the plans there, though that's certainly my recommendation.

**Comment by dan4funnyc** [comment]
As of today, SYNC was at 84% and hard disk usage was at 87GB. Unfortunately, as much as I liked the explorer I was forced to shut it down and remove it. :(
