### ISSUE TITLE
Issue while loading Insight web site

### ISSUE THREAD

**Issue by pdrobek** [bitpay/insight#629]
Please help when accessing the site I get a screen like 

![insight](https://cloud.githubusercontent.com/assets/4559534/8206333/c88590b4-14f8-11e5-83a2-35d3174637fd.jpg)

while api successfully be synchronized. 

![insight1](https://cloud.githubusercontent.com/assets/4559534/8206354/efa88a02-14f8-11e5-970a-6ffb54bf14e7.jpg)

Where can I find the configuration file to the web interface? What steps i have to make to update web interface after i change it?

This page will be a block explorer for http://polcoin.pl/index.php/en/

**Comment by matiu** [comment]
There seems to be a Javascript error on that page.

The the JS console. Be sure you have run grunt / bower / npm as described
on the readme.

On Wed, Jun 17, 2015 at 9:01 AM, Paweł Drobek <notifications@github.com>
wrote:

> Please help when accessing the site I get a screen like
>
> [image: insight]
> <https://cloud.githubusercontent.com/assets/4559534/8206333/c88590b4-14f8-11e5-83a2-35d3174637fd.jpg>
>
> while api successfully be synchronized.
>
> [image: insight1]
> <https://cloud.githubusercontent.com/assets/4559534/8206354/efa88a02-14f8-11e5-970a-6ffb54bf14e7.jpg>
>
> Where can I find the configuration file to the web interface? What steps i
> have to make to update web interface after i change it?
>
> This page will be a block explorer for http://polcoin.pl/index.php/en/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/insight/issues/629>.
>



-- 
BitPay.com

**Comment by pdrobek** [comment]
i ran commands

bower install
grunt compile

once, then copy all files to my webserver and stuck.

**Comment by pdrobek** [comment]
I resolved almost all issues. What is missing  (in my opinion - im not in any way webdev or someone like that)

after i upload all contents from public directory to webserver directory in webbrowser console i saw 404 errors while trying to GET "socket.io.js". I had to create by myself directory "socket.io" and place inside it file named "socket.io.js" from https://cdn.socket.io/socket.io-1.3.5.js. Please consider it as a bug or misconfiguration. 

After that left one error message on webpage 

![insight2](https://cloud.githubusercontent.com/assets/4559534/8230373/cb5e83e6-15bf-11e5-862a-d2b89f24cd61.jpg)

Please tell me where and what should i change in configuration to resolve it? I make changes in 

node_modules/insight-bitcore-api/config/config.js
node_modules/insight-bitcore-api/etc/bitcoind/bitcoin-livenet.conf
node_modules/insight-bitcore-api/lib/BlockExtractor.js
node_modules/insight-bitcore-api/node_modules/bitcore/networks.js

Please any help will be helpfull

**Comment by pdrobek** [comment]
in file 
/webroot/insight/public/views/includes/connection.html
i found
(Tried connecting to bitcoind at {{host}}:{{port}} and failed.)

where {{host}}:{{port}} is some kind of variables, am i right? on screenshot there are no values for them. 

How can i fill it up?

**Comment by pdrobek** [comment]
resolved
