### ISSUE TITLE
change the exchange from bitstamp to something else?

### ISSUE THREAD

**Issue by sigwo** [bitpay/insight#633]
I've gotten the app loading correctly and all information is correct http://nlg.sigwo.com. The last piece is to get pricing BTC/NLG from a valid source. Where would/could I modify insight to pull that information?

**Comment by strataghyst** [comment]
https://github.com/strataghyst/inzicht-api/blob/006789449ea2ac8cbf10b8134ad8bcb09786d759/app/controllers/currency.js

**Comment by braydonf** [comment]
This would be more relevant at the https://github.com/bitpay/insight-api repo, here is the code where additional sources could be added: https://github.com/bitpay/insight-api/blob/master/lib/currency.js
