### ISSUE TITLE
Error: bitcoin JSON-RPC connection rejected: 401 unauthorized

### ISSUE THREAD

**Issue by zekylaf** [bitpay/insight#634]
Hi, I was trying to run insight but I am getting an error. I have bitcoind running, but I get this error, please help me, THANKS! 

ERROR IS: 

 npm start

> insight-bitcore@0.2.5 start /root/test/insight
> INSIGHT_PUBLIC_PATH=public node node_modules/.bin/insight-bitcore-api

    ____           _       __    __     ___          _
   /  _/___  _____(_)___ _/ /_  / /_   /   |  ____  (_)
   / // __ \/ ___/ / __ `/ __ \/ __/  / /| | / __ \/ /
 _/ // / / (__  ) / /_/ / / / / /_   / ___ |/ /_/ / /
/___/_/ /_/____/_/\__, /_/ /_/\__/  /_/  |_/ .___/_/
                 /____/                   /_/

                                                v0.2.13

info: insight server listening on port 3000 in development mode
error: ERROR  Error: bitcoin JSON-RPC connection rejected: 401 unauthorized
    at IncomingMessage.<anonymous> (/root/test/insight/node_modules/insight-bitcore-api/node_modules/bitcore/lib/RpcClient.js:182:18)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
npm ERR! weird error 255
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0

**Comment by carnesen** [comment]
"401 unauthorized" means that the RPC client connected to bitcoind using the wrong username or password. You'll need to pass the correct credentials to insight-api as environment variables BITCOIND_USER and BITCOIND_PASS, or configure your bitcoind to use those variables' default values, 'user' and 'pass', respectively. The configuration code is in this file: https://github.com/bitpay/insight-api/blob/master/config/config.js#L70

**Comment by zekylaf** [comment]
Thanks for your answer! I edited the conf file, and now I am getting this:


npm start

> insight-bitcore@0.2.5 start /root/test/insight
> INSIGHT_PUBLIC_PATH=public node node_modules/.bin/insight-bitcore-api


    ____           _       __    __     ___          _
   /  _/___  _____(_)___ _/ /_  / /_   /   |  ____  (_)
   / // __ \/ ___/ / __ `/ __ \/ __/  / /| | / __ \/ /
 _/ // / / (__  ) / /_/ / / / / /_   / ___ |/ /_/ / / 
/___/_/ /_/____/_/\__, /_/ /_/\__/  /_/  |_/ .___/_/  
                 /____/                   /_/         

                                                v0.2.13

info: insight server listening on port 3001 in development mode
{ '0': [Error: Could not connect to bitcoin via RPC: connect ECONNREFUSED] }
error: ERROR  Error: Could not connect to bitcoin via RPC: connect ECONNREFUSED
    at ClientRequest.<anonymous> (/root/test/insight/node_modules/insight-bitcore-api/node_modules/bitcore/lib/RpcClient.js:207:15)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1547:9)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
npm ERR! weird error 255
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0

**Comment by zekylaf** [comment]
Solved! I delete insight (rm -rf insight) and I delete insight-api(rm -rf insight-api) and clone all again. Then I config the RpcClient.js file and npm start.
 
Thanks you!
