### ISSUE TITLE
Sync from a specific block

### ISSUE THREAD

**Issue by zekylaf** [bitpay/insight#635]
Hi, I am wanting to sync from n block. Example, if I want to sync from the block 364203, what I have to do? 
I was trying to use util/sync.js -D --start 0000000000000000146831090e4c4f7f901a5ed2f830b344449c592a7326e47c

but I always get the same error: 

"  [options] { forceStartFile: undefined,
  forceRPC: undefined,
  startAt: '0000000000000000146831090e4c4f7f901a5ed2f830b344449c592a7326e47c',
  stopAt: undefined }
info: Bitcoin Core version  100200
info: Using RPC sync
info: Resuming sync from block: 0000000000000000146831090e4c4f7f901a5ed2f830b344449c592a7326e47c #364203
info: Got 364203 blocks in current DB, out of 364205 block at bitcoind
info: syncing from RPC (slow)
info: Starting from:  0000000000000000146831090e4c4f7f901a5ed2f830b344449c592a7326e47c
info: status: [99.999%]
error: NEED_SYNC Ignoring block with non existing prev:0000000000000000146831090e4c4f7f901a5ed2f830b344449c592a7326e47c
CRITICAL ERROR:  { status: 'error',
  blockChainHeight: 364205,
  syncPercentage: '99.999',
  height: 364203,
  syncTipHash: undefined,
  error: 'NEED_SYNC Ignoring block with non existing prev:0000000000000000146831090e4c4f7f901a5ed2f830b344449c592a7326e47c',
  type: 'from RPC calls',
  startTs: 1436240849559,
  endTs: null }
"

Please help me, thanks!

**Comment by braydonf** [comment]
This is outdated.
