### ISSUE TITLE
Input marked as unconfirmed for confirmed transaction.

### ISSUE THREAD

**Issue by F483** [bitpay/insight#647]
In input is marked as unconfirmed even though the transaction that is using at is confirmed. Its is extremely unlikely as it would mean an invalid block has been mined, propagated and then additionally confirmed.

https://test-insight.bitpay.com/tx/9ad696b5ae7f7e6c2191827c0dbb33f251aa3bfee512ae6aad06d195b9ecb3df

**Comment by braydonf** [comment]
Should be resolved now, as the input is showing confirmed.
