### ISSUE TITLE
Testnet insight is not working stable

### ISSUE THREAD

**Issue by troggy** [bitpay/insight#650]
Most of the time I receive ``Server not yet ready. Sync Percentage:NaN``.

For example: https://test-insight.bitpay.com/api/addr/2N6rBp9SEocRzZZig89AXS9PSr3SMhRns/utxo

**Comment by matiu** [comment]
Thanks.

I am sorry about this problem. we are using bitcoind 0.9.5, and when it
certain conditions bitcoind go to 'safe mode' and no longer serve RPC
requests. (you can see that in https://test-insight.bitpay.com/status)

It is OK now.  We are scheduled to upgrade bitcoin to 0.11 this week.

matías

On Tue, Aug 4, 2015 at 5:29 AM, Kosta Korenkov <notifications@github.com>
wrote:

> Most of the time I receive Server not yet ready. Sync Percentage:NaN.
>
> For example:
> https://test-insight.bitpay.com/api/addr/2N6rBp9SEocRzZZig89AXS9PSr3SMhRns/utxo
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/insight/issues/650>.
>



-- 
BitPay.com

**Comment by troggy** [comment]
Thanks! BTW https://test-insight.bitpay.com/ is down now

**Comment by ranganath-v** [comment]
https://test-insight.bitpay.com/ is down
