### ISSUE TITLE
Insight install failure - "npm install" did not work - Is there a manual install workaround?

### ISSUE THREAD

**Issue by DRKMSTR** [bitpay/insight#653]
npm http GET https://registry.npmjs.org/insight-bitcore-api
npm http GET https://registry.npmjs.org/bower
npm http GET https://registry.npmjs.org/grunt
npm http GET https://registry.npmjs.org/grunt-cli
npm http GET https://registry.npmjs.org/grunt-contrib-jshint
npm http GET https://registry.npmjs.org/grunt-contrib-concat
npm http GET https://registry.npmjs.org/grunt-contrib-uglify
npm http GET https://registry.npmjs.org/grunt-contrib-watch
npm http GET https://registry.npmjs.org/grunt-macreload
npm http GET https://registry.npmjs.org/grunt-css
npm http GET https://registry.npmjs.org/grunt-markdown
npm http GET https://registry.npmjs.org/grunt-angular-gettext

npm ERR! Error: failed to fetch from registry: bower
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.g (events.js:156:14)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1256:7)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/pi/insight/npm-debug.log npm
npm ERR!
npm ERR! System Linux 3.18.11-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/insight
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: bower
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/insight/npm-debug.log
npm not ok

**Comment by mmitech** [comment]
rm -rf node_modules, then try npm install again

**Comment by SoreGums** [comment]
i see you are using node v0.6.19

I've been having issues myself - then I noticed insight readme says node 0.10.x is required.
after a couple of stop starts, v0.10.40 is working.

so this works as root

````
useradd -m insight
su insight
cd
wget https://nodejs.org/dist/v0.10.40/node-v0.10.40.tar.gz
tar -zxf node-v0.10.40.tar.gz
cd node-v0.10.40
./configure --prefix=$HOME/.local
make
make install
cd
ln -s .local/lib/node_modules .node_modules
export PATH=$HOME/.local/bin:$PATH
git clone https://github.com/bitpay/insight.git && cd insight
npm install
INSIGHT_FORCE_RPC_SYNC=1 INSIGHT_NETWORK=livenet BITCOIND_USER=user BITCOIND_PASS=pass INSIGHT_PUBLIC_PATH=public m start
````
