### ISSUE TITLE
Can't connect to coind to get live updates from the p2p network.

### ISSUE THREAD

**Issue by mmitech** [bitpay/insight#654]
I am struggling with this for a couple of hours now: 

Can't connect to coind to get live updates from the p2p network. (Tried connecting to bitcoind at 127.0.0.1:5837 and failed.)

in the log I see { '0': 'connecting to 127.0.0.1:5837' } after a while { '0': 'disconnected from peer 127.0.0.1:5837' }.

I can telnet 127.0.0.1 5837 and 0.0.0.0 5837 
 telnet 127.0.0.1 5837
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.

I double checked the magic again, and it is d9e6e7e5 exactly like in the source code https://github.com/Leocoin-project/LEOcoin/blob/master/src/main.cpp#L3023
The Protocol version is 70000 same as in the code 
"version" : "v1.3.0.0-L32a928e-leo-enhanced",
    "protocolversion" : 70000,
    "walletversion" : 60000,
    "balance" : 0.00000000,
    "newmint" : 0.00000000,
    "stake" : 0.00000000,
    "blocks" : 605091,
    "moneysupply" : 65289528.44299800,
    "connections" : 9,
    "proxy" : "",
    "ip" : "217.26.192.84",
    "difficulty" : 0.18828001,
    "testnet" : false,
    "keypoololdest" : 1439130316,
    "keypoolsize" : 102,
    "paytxfee" : 0.00001000,
    "errors" : "."

but I can't get it to work !!! any suggestion ? did I miss anything ?

**Comment by mmitech** [comment]
Fixed, somehow I mixed the magic numbers for the mainnet with the testnet.

Otherwise for people having any trouble connecting to p2p, go through the steps that I've listed and double check your config.

**Comment by doged** [comment]
lol at best i connect to the p2p for a day or two.. at worst it takes restarting over and over every 30 seconds, and sometiems takes 20-50 tries to get it to connect and stay (for a few hours/days)

i see this issue all over github..

**Comment by mmitech** [comment]
Hello, yes I thought it worked as well, but after few hours the p2p was dead again, I found out that the problem is with the coin daemon (sonething with magix number) and it is not with Insight.
