### ISSUE TITLE
Public testnet Insight is in Safe mode?

### ISSUE THREAD

**Issue by troggy** [bitpay/insight#656]
It doesn't work properly returning
````
Safe mode: Warning: The network does not appear to fully agree! Some miners appear to be experiencing issues.
````

**Comment by matiu** [comment]
it should be ok now, thanks.

On Fri, Aug 21, 2015 at 2:18 AM, Kosta Korenkov <notifications@github.com>
wrote:

> It doesn't work properly returning
>
> Safe mode: Warning: The network does not appear to fully agree! Some miners appear to be experiencing issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/insight/issues/656>.
>



-- 
BitPay.com
