### ISSUE TITLE
p2p doesnt stay connected

### ISSUE THREAD

**Issue by doged** [bitpay/insight#676]
i know just about every insight user has this problem, where the p2p only stays connected for 30 seconds to a few days, but doesnt just "stay connected"

was there a commit for this?

i have to restart my insight explorer every few hours, or at best, every 2-3 days..

**Comment by zekylaf** [comment]
Hi, I am having the same problem. If you find a solution, please post it here :)

thanks

**Comment by doged** [comment]
@zekylaf yeah it's not just us though, it's everyone running insight with an altcoin.. i've been reviewing and trying to figure out why the communication ends, but to no avail thus far..

**Comment by zekylaf** [comment]
@doged I am running Insight with bitcoin. This problem not only happens with altcoins. We have not answer from the developers.

**Comment by braydonf** [comment]
No longer an issue with the latest release.
