### ISSUE TITLE
Displays incorrect sync percentage

### ISSUE THREAD

**Issue by braydonf** [bitpay/insight#680]
When syncing the percentage will be usually higher than what will appear in logs.

**Comment by bitjson** [comment]
For now it'd be great if Insight displayed the underlying Bitcoind's sync percentage rather than it's own. We might want to take a design pass over Insight later to make both clearer.

**Comment by braydonf** [comment]
It would be great to be able to display both an the status page.

**Comment by pnagurny** [comment]
FIxed here: https://github.com/bitpay/insight-api/pull/410
