### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by scriptzteam** [bitpay/insight#681]
root@xyz~# npm install -g bitcore-node
npm WARN engine bitcore-node@0.2.5: wanted: {"node":"^0.12"} (current: {"node":"                                                                             0.10.25","npm":"1.4.21"})
/
npm WARN engine hawk@3.1.0: wanted: {"node":">=0.10.32"} (current: {"node":"0.10                                                                             .25","npm":"1.4.21"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":                                                                             "0.10.25","npm":"1.4.21"})
npm WARN engine boom@2.9.0: wanted: {"node":">=0.10.40"} (current: {"node":"0.10                                                                             .25","npm":"1.4.21"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.1                                                                             0.25","npm":"1.4.21"})
|
> leveldown@1.4.2 install /usr/local/lib/node_modules/bitcore-node/node_modules/                                                                             leveldown
> prebuild --download

/usr/bin/env: node: No such file or directory
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

**Comment by braydonf** [comment]
Node.js v0.12 is currently only supported, more details here: https://bitcore.io/guides/full-node

**Comment by scriptzteam** [comment]
nvm install 0.12
nvm use 0.12
npm install -g bitcore-node
> leveldown@1.4.2 install /root/.nvm/versions/node/v0.12.9/lib/node_modules/bitcore-node/node_modules/leveldown
> prebuild --download

sh: prebuild: command not found
npm ERR! Linux 3.14.32-xxxx-grs-ipv6-64
npm ERR! argv "/root/.nvm/versions/node/v0.12.9/bin/node" "/root/.nvm/versions/node/v0.12.9/bin/npm" "install" "-g" "bitcore-node"
npm ERR! node v0.12.9
npm ERR! npm  v2.14.9
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! leveldown@1.4.2 install: `prebuild --download`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the leveldown@1.4.2 install script 'prebuild --download'.
npm ERR! This is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --download
npm ERR! You can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/insight-ui/bitcore-node/npm-debug.log
