### ISSUE TITLE
setup insight

### ISSUE THREAD

**Issue by zouchao2010** [bitpay/insight#688]
npm install -g bitcore-node
bitcore-node create mynode
cd mynode
bitcore-node add insight-api
bitcore-node add insight-ui
bitcore-node start
Open a web browser to http://localhost:3001/insight/

why response "Cannot GET /insight/"

**Comment by zouchao2010** [comment]
I know!
It should be "install" not "add"
bitcore-node install insight-api
bitcore-node install insight-ui

**Comment by braydonf** [comment]
We should update the docs and also link to https://bitcore.io/guides/full-node

**Comment by ser** [comment]
it's still not updated :( I spent 30 minutes seeking for the reason why UI does not work :(
