### ISSUE TITLE
Insight Down

### ISSUE THREAD

**Issue by jprichardson** [bitpay/insight#692]
Visiting https://insight.bitpay.com/ returns:

> Can't connect to bitcoind to get live updates from the p2p network. (Tried connecting to bitcoind at localhost:8333 and failed.)

Visiting https://insight.bitpay.com/api/peer, `connected` returns `false` when the expectation is for it to return `true`.

**Comment by matiu** [comment]
Thanks. It is fixed now.

**Comment by troggy** [comment]
@matiu Same error right now: https://insight.bitpay.com/status
