### ISSUE TITLE
Invalid Transaction ID

### ISSUE THREAD

**Issue by dhiru22** [bitpay/insight#777]
I have sent my 0.1 btc to this address 1FKGDdbkP1RNGMwrNAnNTarxRrFczun3gn via  my unicoin wallet transaction is succesfull but showing hash: wait
Invalid Transaction ID: waiting..
[Home _ Insight.pdf](https://github.com/bitpay/insight-ui/files/1023162/Home._.Insight.pdf)

please any body solve my issue

**Comment by sesam** [comment]
Recommend close
