### ISSUE TITLE
Stuck on Loading Address Information...

### ISSUE THREAD

**Issue by sunk818** [bitpay/insight#814]
This is the pool wallet address for pool.artbyte.me
http://explorer.artbyte.me/address/AM8cCX3D4KKJLvubk33pv5dpt6534iTA1S

Is there a way to limit the number of records the query selects and perhaps bring in the most recent (top 50)?

There are over 390k transactions associated with the wallet address.

**Comment by kleetus** [comment]
This request should be paginated 10 records per page.

**Comment by sunk818** [comment]
To bring up 390k records takes very long time... Even if only fort ten records are shown
