### ISSUE TITLE
Transaction not Found

### ISSUE THREAD

**Issue by TheProphetz** [bitpay/insight#831]
Hello,
My Payment Transaction is not found anymore on the E-mail i recieved. First i waited hours for the Confirmation wich is probably of the low fee, but now the Transaction is gone and the Payment not back in my Wallet.
Need Help

**Comment by kleetus** [comment]
I would advise re-broadcasting the transaction after about 72 hours with a higher fee. This would not be insight-related.

**Comment by TheProphetz** [comment]
why 72 hours i want it now. Please i need it asap

2017-11-29 20:37 GMT+01:00 Chris Kleeschulte <notifications@github.com>:
