### ISSUE TITLE
testnet ltc is not transcated using litecore-exploeres

### ISSUE THREAD

**Issue by potadibyo** [bitpay/insight#866]
var explorers = require('litecore-explorers');//'testnet'
var insight = new explorers.Insight('testnet');
insight.getUtxos('mkRDbgTw4YkSojQJfBmGvoEBibohz87AMY', function(err, utxos) {
  if (err) {
   return console.log(err);
  } else {
    console.log(utxos);
     var transaction = litecore.Transaction()
  .from(utxos)
  .to('n3kpPEHxTeX3KuKeX7WMGewuZuA18XPnNi', 500000)
  .change('mkRDbgTw4YkSojQJfBmGvoEBibohz87AMY')
  .fee(10000)
  .sign(privatekey);
      var seraliseee = transaction.serialize();
	console.log(seraliseee);
	
	
		//tx.addData()
		insight.broadcast(seraliseee ,function(err, returnTxId){
			if(err){

			console.log(err);
		}else{
			//res.send("uccessfull broadcast"+"<br>" +returnTxId);	
			console.log('Successfull broadcast ');	
			    console.log(returnTxId);
			//////res.send("Successfull broadcast "+"<br> "+ returnTxId );
		     }							
		});
      
  }
});

Please help me to solve the problem....

**Comment by ActoMatics** [comment]
Try this:
const getAddBalance = (address, coin) => {
  let network;

  // find the right network 
  if (coin == 'btc')
    network = 'BTCTEST';
  if (coin == 'ltc')
    network = 'LTCTEST';

  const url = 'https://chain.so/api/v2/get_address_balance/' + network + '/' + address;

  return axios.get(url)
    .catch(err => {
      console.error(err.response.data);
      return err;
    })
    .then(res => {
      return res.data.data.confirmed_balance;
    });
}

**Comment by matiu** [comment]
LTC is not supported at insight.
