### ISSUE TITLE
Send DigiByte wallet access

### ISSUE THREAD

**Issue by wfurnival** [bitpay/insight#876]
Greetings
 
Is there a way to allow wallet access to products like Digibyte without downloading a full wallet? 

For example, www.myetherwallet.com, allows users to login and send / receive ether or ERC20 tokens, could that be done for other projects too on https://digiexplorer.info/? Bitcoin has a similiar service at blockchain.info. 

Kind regards

WF

**Comment by gabegattis** [comment]
This is not digibyte.
