### ISSUE TITLE
Can't find the bitcoin cash api link

### ISSUE THREAD

**Issue by ArseniyChern** [bitpay/insight#903]
Ok so I need an api for bitcoin cash where I could input a public key and get a users balance. Insight seems to be what I need but I need to run a local server in order for it to work, is there any way of not doing that and using an api hosted on a different server?

Probably a super dumb question. Regardless I appreciate any help.

**Comment by gabegattis** [comment]
Insight does not expose an api for public keys. You could use bitcore-lib to convert public keys to addresses and then look up the balance by address.

We run insight at https://insight.bitpay.com

**Comment by lawrencegs** [comment]
How about address? Sorry if this sounds silly, I tried to navigate but can't figure out if there's public facing API on Insight.

**Comment by alwaysAn0n** [comment]
@ArseniyChern @lawrencegs 

Most of the functionality you need to develop a BCH application can be found spread out amongst the many Bitpay libraries like insight.  You often have to dig for the code that provides the specific functionality you need and "Frankenstein" it together though.  This is a symptom of Bitpay's slow response to the Bitcoin fork.  Sadly they haven't made a great enough effort to give Bitcoin developers the necessary tools to continue building on Bitcoin Cash.

If you're serious about building on BCH and don't need the additional overhead (multiple currency support) found in the Bitpay libraries, I recommend you check out BitBox @ https://www.bitbox.earth or https://github.com/bigearth/ .  They have an enormous suite of tools, all up to date, and all ready for building production ready BCH applications.

On a related note, there's a pretty serious group of BCH developers organizing on the Bitcoin Cash Fund's Discord instance at http://ambassador.cash .  You're invited to join us.

**Comment by dhjw** [comment]
https://bch-insight.bitpay.com/api/addr/...

**Comment by dila93** [comment]
https://test-bch-insight.bitpay.com/api/addr/  
for tesnet

**Comment by ActoMatics** [comment]
Anyone know what is the API for send transaction id?
I tried to :  url =  'url = 'https://test-bch-insight.bitpay.com/tx/send/' + signedTx;'
But no luck, it 400 error

**Comment by matiu** [comment]
400 is a client-side error.

You need to POST the transaction.
