### ISSUE TITLE
How to sync insight API with bitcored

### ISSUE THREAD

**Issue by Smurfy303** [bitpay/insight#914]
I am using bitcoin-node-api module of nodejs for that I am running bitcored and start my server which runs fine.

I have transferred money to address which generated by using http://localhost:1111/bitcoin/api/getnewaddress API . For that I refer **bitcoin-node-api**.

But, When I check the transactions by using **listreceivedbyaddress** it gives me an output like,
"result": [
        {
            "address": "136auV5QyASpX14YLdgiqYEkQH8puAXnE2",
            "account": "kiran",
            **"amount": 0,**
            "confirmations": 0,
            "label": "kiran",
            **"txids": []**
        }
]

Why it not showing me balance or txs ??

**Comment by Smurfy303** [comment]
Hi! Dev's, anybody here?

**Comment by Smurfy303** [comment]
??

**Comment by matiu** [comment]
Please stop repeating questions or you will be banned.

https://github.com/bitpay/insight-api/issues/577#issuecomment-380409997
