### ISSUE TITLE
API documentation?

### ISSUE THREAD

**Issue by gutenye** [bitpay/insight#923]
Hi, 

The link(https://github.com/bitpay/insight#api) listed in the website(https://insight.is/) is outdated. 
Is there a new link? Or maybe I can just read the source code :)

**Comment by matiu** [comment]
https://github.com/bitpay/insight#api

is the most updated docs. Please send a PR if you see something outdated. thanks a lot!!

**Comment by gutenye** [comment]
@matiu I think you missed my point, the link you given shows the this repository, but does not contain any documentation related to the API.

<img width="789" alt="screen shot 2018-04-24 at 8 45 52 pm" src="https://user-images.githubusercontent.com/377544/39187680-85d40262-4800-11e8-9e4f-9379757e0447.png">

**Comment by matiu** [comment]
Sorry, I  meant https://github.com/bitpay/insight-api 
(see the Readme bellow)
