### ISSUE TITLE
Captcha on API!!!

### ISSUE THREAD

**Issue by Piterden** [bitpay/insight#965]
I trying to resolve an information about a wallet through API request `https://insight.litecore.io/api/addr/LQFJLDNtScTn77BoWP8KpUr3taF1xTA5aw` and I have the next page:
![image](https://user-images.githubusercontent.com/5930429/45288954-9cc55c80-b4f4-11e8-8ebd-8607672a83af.png)
Could you explain me please, how should my software avoid it?

**Comment by matiu** [comment]
litecore.io is not related to this repo.

That's a Cloudflare captcha.  Try googling "cloudflare captcha"
