### ISSUE TITLE
All Addresses return Invalid Address

### ISSUE THREAD

**Issue by makeholer** [bitpay/insight#976]
Just finished the sync, most transactions doesn`t show the values and the input addresses are Unparsed.

But the main problem is there every address i try to search return Invalid Address, i don't know what can be wrong.

Using:

bitcoind v0.17

the explorer link actually is:

http://bitcoinvalor.com.br:3001/insight/

Any tips?

**Comment by matiu** [comment]
Are you using  bech32 addresses? You fan disable them in bitcoin.conf

**Comment by makeholer** [comment]
The problem seems to be the bitcoind version, it worked after i purged it and reinstalled bitcore alone.
